name: Callee

on:
  workflow_call:
    inputs:
      input-1:
        description: "A number input"
        required: false
        type: number
        default: 42

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Use the input
        run: |
          echo "The input value is ${{ inputs.input-1 }}"
